site :opscode

metadata
cookbook 'yum'
cookbook 'nginx'
cookbook 'redis'
cookbook 'rbenv',
  :git => 'git://github.com/fnichol/chef-rbenv.git', :branch => 'v0.7.2'
cookbook 'mongodb', :git => 'git://github.com/edelight/chef-mongodb.git'
cookbook 'python'

